-- AlterTable
ALTER TABLE "Library" ADD COLUMN     "acs" INTEGER DEFAULT 0,
ADD COLUMN     "chairs" INTEGER DEFAULT 0,
ADD COLUMN     "fans" INTEGER DEFAULT 0,
ADD COLUMN     "latitude" DOUBLE PRECISION,
ADD COLUMN     "longitude" DOUBLE PRECISION,
ADD COLUMN     "tables" INTEGER DEFAULT 0;
